[features]
seeds = false
skip-lint = false

[programs.mainnet]
aistm7_token = "AISTM7TokenProgramID11111111111111111111111111111111"

[programs.devnet]
aistm7_token = "AISTM7TokenProgramID11111111111111111111111111111111"

[programs.localnet]
aistm7_token = "AISTM7TokenProgramID11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "AHtgzX45WTKfkPG53L6WYhGEXwQkN1BVknET3sVsLL8J"  # Pyth SOL/USD price feed

[workspace]
types = "target/types/aistm7_token"
members = [
    "programs/aistm7_token"
]